### ISSUE TITLE
Compat issue with arcananovum (Fabric 1.21.1 with 0.16.7 / Hugh modpack)

### ISSUE THREAD

**Issue by suerion** [raevendev/Quantum#3]
Hey, i will create the issue here, because it gives me an issue on WorldCreating with Quantum. I had Tried on an hugh modpack to create a new world, but the server has instant crash after executing the command.

Latest.log
https://mclo.gs/cqAAqTV

Crash File:
https://mclo.gs/fTapMz5

i will also create a Issue on Arcana Novum Linked with this issue.

If you ned more informations, i can test it, because it is an DEV Enviroment on my side.

**Comment by Unreal852** [comment]
It appears that the crash is due to a bug in the ArcanaNovum mod. The developer has mentioned that a fix is on the way, and I’ll wait to see if it resolves the issue.

**Comment by suerion** [comment]
> It appears that the crash is due to a bug in the ArcanaNovum mod. The developer has mentioned that a fix is on the way, and I’ll wait to see if it resolves the issue.

Hey, yeah i will try it, if this is fixed, i will close the issue, if not, i will come direct back to you

**Comment by suerion** [comment]
@Unreal852 it look, that the issue is gone, now i would look forward to all features you will add in future,

thanks for your work :)
